# events.toml

# [Wake_Up_30min]
# direction = "ON"
# time_unit = "m"
# duration = 1800  # 30 minutes
# completion_time = "07:00"
# start_time = "06:30"
# recurrence = "weekdays"
# last_executed = ""
# color_change = true
# color_direction = "COOL_TO_WARM"
# start_color = [0.33, 0.34]
# end_color = [0.526, 0.413]
# color_transition_time = 450  # 7.5 minutes (25%)
# brightness_transition_time = 1350  # 22.5 minutes (75%)

# [Sleep_Time_30min]
# direction = "OFF"
# time_unit = "m"
# duration = 1800  # 30 minutes
# completion_time = "22:30"
# start_time = "22:00"
# recurrence = "everyday"
# last_executed = ""
# color_change = true
# color_direction = "WARM_TO_COOL"
# start_color = [0.526, 0.413]
# end_color = [0.33, 0.34]
# color_transition_time = 450  # 7.5 minutes (25%)
# brightness_transition_time = 1350  # 22.5 minutes (75%)

# [Wake_Up_2hr]
# direction = "ON"
# time_unit = "m"
# duration = 7200  # 2 hours
# completion_time = "07:00"
# start_time = "05:00"
# recurrence = "weekdays"
# last_executed = ""
# color_change = true
# color_direction = "COOL_TO_WARM"
# start_color = [0.33, 0.34]
# end_color = [0.526, 0.413]
# color_transition_time = 3600  # 1 hour (50%)
# brightness_transition_time = 3600  # 1 hour (50%)

# [Sleep_Time_2hr]
# direction = "OFF"
# time_unit = "m"
# duration = 7200  # 2 hours
# completion_time = "22:30"
# start_time = "20:30"
# recurrence = "everyday"
# last_executed = ""
# color_change = true
# color_direction = "WARM_TO_COOL"
# start_color = [0.526, 0.413]
# end_color = [0.33, 0.34]
# color_transition_time = 3600  # 1 hour (50%)
# brightness_transition_time = 3600  # 1 hour (50%)

# [Wake_Up_90min]
# direction = "ON"
# time_unit = "m"
# duration = 5400  # 90 minutes
# completion_time = "07:00"
# start_time = "05:30"
# recurrence = "weekdays"
# last_executed = ""
# color_change = true
# color_direction = "COOL_TO_WARM"
# start_color = [0.33, 0.34]
# end_color = [0.526, 0.413]
# color_transition_time = 1800  # 30 minutes (33%)
# brightness_transition_time = 3600  # 60 minutes (67%)

# [Sleep_Time_90min]
# direction = "OFF"
# time_unit = "m"
# duration = 5400  # 90 minutes
# completion_time = "22:30"
# start_time = "21:00"
# recurrence = "everyday"
# last_executed = ""
# color_change = true
# color_direction = "WARM_TO_COOL"
# start_color = [0.526, 0.413]
# end_color = [0.33, 0.34]
# color_transition_time = 1800  # 30 minutes (33%)
# brightness_transition_time = 3600  # 60 minutes (67%)
