# wakeup.toml

# Each task is a table with time, action, and optional args

[[schedule]]
time = "07:57"
action = "warm"

[[schedule]]
time = "07:58"
action = "0%"

[[schedule]]
time = "07:59"
action = "ON"

[[schedule]]
time = "08:00"
action = "100%"
args = "-time 60m"
